/*
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 *     http://duracloud.org/license/
 */
package org.duracloud.serviceconfig;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;

/**
 * @author: Bill Branan
 * Date: 7/14/11
 */
@XmlRootElement
public class ServiceReportList extends ServiceReportBase {

    @XmlElement(name = "serviceReport")
    private List<String> serviceReportList;

    // Required for JAXB
    private ServiceReportList() {
    }

    public ServiceReportList(List<String> serviceReportList) {
        this.serviceReportList = serviceReportList;
        this.schemaVersion = SCHEMA_VERSION;
    }

    public List<String> getServiceReportList() {
        return serviceReportList;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        ServiceReportList that = (ServiceReportList) o;

        if (serviceReportList != null ? !serviceReportList
            .equals(that.serviceReportList) : that.serviceReportList != null) {
            return false;
        }

        return true;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public int hashCode() {
        return serviceReportList != null ? serviceReportList.hashCode() : 0;
    }
}
